FROM python:3.11-slim

RUN apt-get update && apt-get install -y openjdk-21-jre-headless && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64

RUN pip install --no-cache-dir pyspark==3.5.0 delta-spark pandas pyarrow pyyaml

WORKDIR /app

COPY pipeline/ ./pipeline/
COPY config/ ./config/

ENV PYTHONPATH=/app

CMD ["python", "-m", "pipeline.run_all"]